apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.3.2
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      initContainers:
        - name: busybox
          image: busybox:1.35
          command: []
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
